### ISSUE TITLE
Implement groups of tasks

### ISSUE THREAD

**Issue by mkorvas** [RichardLitt/wyrd-django-dev#1]
User should be able to group tasks into groups of several types, especially:
1. ordered group: tasks ordered by time they have to be fulfilled (imagine a recipe);
2. disjunctive group: any of the tasks suffices to be done
3. conjunctive group: all the tasks need to be done and they belong together.

Prerequisites and enablements should then be specified not only in terms of tasks, but (also) in terms of groups of tasks.

(Look at how Gentoo's ebuilds cope with dependencies -- they build on experience, and thus are worth following.)

**Comment by RichardLitt** [comment]
No longer maintained. Thank you, anyway, @mkorvas. Hope you're doing well. :)
